#!/usr/bin/env python3
# =============================================================================
# mint_keys.py -- mint the JWT secret + anon/service_role keys, stdlib only
# =============================================================================
# Darrell 2026-08-14, after Supabase restricted the project for exceeding the
# free-tier egress quota and locked every user out of all four apps for 86
# hours: "I'm not paying them... other options!!!!!!!?" then "start the NAS
# supabase stack."
#
# Self-hosted Supabase needs three secrets that must AGREE with each other:
#   JWT_SECRET         -- the HMAC key the whole stack verifies against
#   ANON_KEY           -- a JWT with role=anon,         signed by JWT_SECRET
#   SERVICE_ROLE_KEY   -- a JWT with role=service_role, signed by JWT_SECRET
#
# If the keys are not signed by that exact secret, every request 401s with a
# message that says nothing useful. Minting them together, once, is the whole
# job of this file.
#
# WHY STDLIB ONLY (DR-0083 shape, and a measured constraint): the NAS runs
# Python 3.8.15 and root CANNOT import packages from dpoe's per-user
# site-packages -- measured by nas-health run 31817289739, and the reason the
# transcript drain has been dead since Aug 11. An installer that needs `pip
# install PyJWT` is an installer that fails on this box. A JWT is just
# base64url(header).base64url(payload).HMAC-SHA256 -- hmac, hashlib, base64 and
# json are all we need, and all ship with Python.
#
# IDEMPOTENCE IS A SAFETY PROPERTY HERE, NOT A CONVENIENCE. Re-minting a
# JWT_SECRET over a LIVE stack invalidates every issued session at once --
# every user signed out, and any client holding a stale anon key gets 401 until
# it reloads. So this refuses to overwrite an existing env file unless asked
# explicitly. Same discipline as nas-property-photos ("Token kept, never
# regenerated over a live one").
#
# Selftest: python3 mint_keys.py --selftest
# Mint:     python3 mint_keys.py --out /volume1/docker/supabase/.env
# =============================================================================
import base64
import hashlib
import hmac
import json
import os
import secrets
import sys

# 10 years. These are infrastructure keys, not user sessions; a self-hosted
# stack that silently expires its own anon key in an hour is a stack that dies
# at 3am for a reason nobody can find.
TEN_YEARS_SECONDS = 10 * 365 * 24 * 3600


def b64url(raw):
    """base64url WITHOUT padding -- the '=' padding is invalid in a JWT."""
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def mint_jwt(secret, role, issued_at, ttl=TEN_YEARS_SECONDS):
    """A signed HS256 JWT carrying the role Supabase's policies switch on."""
    header = {"alg": "HS256", "typ": "JWT"}
    payload = {
        "role": role,
        "iss": "supabase",
        "iat": int(issued_at),
        "exp": int(issued_at) + int(ttl),
    }
    # separators=(",", ":") -- no incidental whitespace, so the signature is
    # reproducible across Python versions.
    segments = [
        b64url(json.dumps(header, separators=(",", ":"), sort_keys=True).encode()),
        b64url(json.dumps(payload, separators=(",", ":"), sort_keys=True).encode()),
    ]
    signing_input = ".".join(segments).encode("ascii")
    sig = hmac.new(secret.encode("utf-8"), signing_input, hashlib.sha256).digest()
    segments.append(b64url(sig))
    return ".".join(segments)


def verify_jwt(secret, token):
    """Verify + decode. Returns the payload, or raises. Used by the selftest so
    the proof is a real round-trip, not a string comparison."""
    parts = token.split(".")
    if len(parts) != 3:
        raise ValueError("not a three-part JWT")
    signing_input = ".".join(parts[:2]).encode("ascii")
    expected = hmac.new(secret.encode("utf-8"), signing_input, hashlib.sha256).digest()
    got = base64.urlsafe_b64decode(parts[2] + "=" * (-len(parts[2]) % 4))
    if not hmac.compare_digest(expected, got):
        raise ValueError("signature mismatch")
    pad = "=" * (-len(parts[1]) % 4)
    return json.loads(base64.urlsafe_b64decode(parts[1] + pad))


def mint_all(now):
    """The three secrets, generated together so they agree by construction."""
    jwt_secret = secrets.token_urlsafe(48)          # >= 32 chars, GoTrue's floor
    return {
        "POSTGRES_PASSWORD": secrets.token_urlsafe(32),
        "JWT_SECRET": jwt_secret,
        "ANON_KEY": mint_jwt(jwt_secret, "anon", now),
        "SERVICE_ROLE_KEY": mint_jwt(jwt_secret, "service_role", now),
        "DASHBOARD_PASSWORD": secrets.token_urlsafe(24),
        "SECRET_KEY_BASE": secrets.token_urlsafe(48),   # realtime
        "VAULT_ENC_KEY": secrets.token_urlsafe(24)[:32],
    }


def render_env(values):
    lines = [
        "# Generated by infra/nas-supabase/mint_keys.py. DO NOT COMMIT.",
        "# Re-minting JWT_SECRET over a live stack signs out every user at once.",
    ]
    for k in sorted(values):
        lines.append("{}={}".format(k, values[k]))
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ selftest
def selftest():
    passed, failed = 0, 0

    def check(label, cond):
        nonlocal passed, failed
        if cond:
            passed += 1
            print("PASS " + label)
        else:
            failed += 1
            print("FAIL " + label)

    now = 1_700_000_000  # fixed, so the test is deterministic
    v = mint_all(now)

    check("mints every key the stack needs", all(
        v.get(k) for k in ("POSTGRES_PASSWORD", "JWT_SECRET", "ANON_KEY",
                           "SERVICE_ROLE_KEY", "SECRET_KEY_BASE", "VAULT_ENC_KEY")))
    check("JWT_SECRET clears GoTrue's 32-char floor", len(v["JWT_SECRET"]) >= 32)
    check("VAULT_ENC_KEY is exactly 32 chars", len(v["VAULT_ENC_KEY"]) == 32)

    # The property that actually matters: the keys verify against the secret.
    anon = verify_jwt(v["JWT_SECRET"], v["ANON_KEY"])
    svc = verify_jwt(v["JWT_SECRET"], v["SERVICE_ROLE_KEY"])
    check("ANON_KEY verifies against JWT_SECRET and carries role=anon",
          anon["role"] == "anon")
    check("SERVICE_ROLE_KEY verifies and carries role=service_role",
          svc["role"] == "service_role")
    check("keys expire far out, not in an hour", anon["exp"] - anon["iat"] > 5 * 365 * 24 * 3600)

    # PROVEN-TO-CATCH: a key minted under a DIFFERENT secret must be rejected.
    # This is the failure this file exists to prevent -- a mismatched trio 401s
    # every request with an unhelpful message.
    other = mint_jwt("a-completely-different-secret-value-here", "anon", now)
    try:
        verify_jwt(v["JWT_SECRET"], other)
        check("CATCHES a key signed by the wrong secret", False)
    except ValueError:
        check("CATCHES a key signed by the wrong secret", True)

    # PROVEN-TO-CATCH: a tampered payload must be rejected.
    head, _pay, sig = v["ANON_KEY"].split(".")
    forged = ".".join([head, b64url(json.dumps(
        {"role": "service_role", "iss": "supabase", "iat": now, "exp": now + 99},
        separators=(",", ":"), sort_keys=True).encode()), sig])
    try:
        verify_jwt(v["JWT_SECRET"], forged)
        check("CATCHES a payload escalated anon -> service_role", False)
    except ValueError:
        check("CATCHES a payload escalated anon -> service_role", True)

    check("no '=' padding leaks into any segment",
          "=" not in v["ANON_KEY"] and "=" not in v["SERVICE_ROLE_KEY"])
    check("two mints never collide", mint_all(now)["JWT_SECRET"] != v["JWT_SECRET"])

    env = render_env(v)
    check("env renders one KEY=VALUE per line", "JWT_SECRET=" in env and "\n\n" not in env.strip())
    check("env warns against committing", "DO NOT COMMIT" in env)

    print("\n{}/{} passed".format(passed, passed + failed))
    return 1 if failed else 0


def main(argv):
    if "--selftest" in argv:
        return selftest()

    out = None
    if "--out" in argv:
        out = argv[argv.index("--out") + 1]
    if not out:
        print("usage: mint_keys.py --out <path/to/.env> [--force]", file=sys.stderr)
        return 2

    # THE SAFETY GATE. An existing env file means a live stack with live
    # sessions; overwriting it signs everyone out. The installer relies on this
    # refusal to stay idempotent across every services-sync cycle.
    if os.path.exists(out) and "--force" not in argv:
        print("mint_keys: {} already exists - keeping it (re-minting would sign out every user)".format(out))
        return 0

    import time
    values = mint_all(time.time())
    d = os.path.dirname(out)
    if d:
        os.makedirs(d, exist_ok=True)
    # 0600 before writing: secrets must never be world-readable on a shared NAS.
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(render_env(values))
    print("mint_keys: wrote {} (0600)".format(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
