// @vitest-environment node
// L144 — A False Balance. Verbatim KJV, and the claims this lesson may never
// lose — including the correction made to its own author's premise.
// =============================================================================
// Spoken by Darrell 2026-09-12: money is generated by the individuals capable of
// sustaining the payments; refusing ownership to the capable because you want
// specific people to own limits the growth of the nation; you cannot undermine
// certain groups, let only certain ones win, and still expect a beautiful
// environment for everyone. He named the lending detail and asked for it to be
// RESEARCHED rather than agreed with. He gave the older men's testimony about
// sending somebody else in to the bank. He widened it to all industries and
// named the posture as taking advantage, then refined it himself mid-stream:
// maybe not every company, but in every industry the voices are not heard. He
// named the purpose he sees underneath — the children were needed to need jobs.
// He named the removal of federal enforcement. And he closed where a believer
// closes: vengeance is Yahweh's, and speaking truth to what is real still
// matters to Him.
//
// WHY THIS FILE IS STRICT. The lesson CORRECTS a premise its own author said he
// believed fully, and it does so because he asked for research rather than
// agreement. That correction is the single most likely thing for a later edit
// to soften back into simple agreement, so it is pinned hardest here.
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LIVING_LESSONS_MODULES, LIVING_LESSONS_META } from '../lib/living-lessons-class.js';
import { AGE_BANDS, resolveForAge } from '../lib/learn-framework.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(HERE, '..', 'lib', 'living-lessons-class.js'), 'utf8');
const ID = 'll144-a-false-balance-capable-hands-and-the-capital-they-were-never-given';
const start = src.indexOf(`id: '${ID}'`);

const l = (() => {
  const rest = src.slice(start);
  const nextLesson = rest.indexOf("\n  {\n    id: 'll");
  const arrayEnd = rest.indexOf('\n  },\n];');
  const ends = [nextLesson, arrayEnd].filter((i) => i > -1);
  return ends.length ? rest.slice(0, Math.min(...ends)) : rest;
})();

const KJV_DIR = join(HERE, '..', '..', 'public', 'bible', 'kjv');
const { BY_LINE, BY_SPACE } = (() => {
  let byLine = '';
  let bySpace = '';
  for (const f of readdirSync(KJV_DIR)) {
    if (!f.endsWith('.json') || f === 'index.json') continue;
    const book = JSON.parse(readFileSync(join(KJV_DIR, f), 'utf8'));
    for (const ch of book.chapters) { byLine += `${ch.join('\n')}\n`; bySpace += `${ch.join(' ')} `; }
  }
  return { BY_LINE: byLine, BY_SPACE: bySpace };
})();
const inKjv = (part) => BY_LINE.includes(part) || BY_SPACE.includes(part);
const verse = (book, chapter, num) => {
  const file = join(KJV_DIR, `${book.replace(/\s+/g, '')}.json`);
  return JSON.parse(readFileSync(file, 'utf8')).chapters[chapter - 1][num - 1];
};

const withoutStories = (text) => {
  const i = text.indexOf('stories: [');
  if (i < 0) return text;
  const j = text.indexOf('\n    ],', i);
  return text.slice(0, i) + text.slice(j < 0 ? i : j);
};
const quotedSpans = (text) => {
  const body = text.replace(/\\'/g, "'");
  const marks = (body.match(/"/g) || []).length;
  const parts = body.split('"');
  const spans = [];
  for (let i = 1; i < parts.length; i += 2) spans.push(parts[i]);
  return { spans, balanced: marks % 2 === 0 };
};
const mod = () => LIVING_LESSONS_MODULES.find((x) => x.id === ID);
const ourVoice = () => {
  const m = mod();
  return [m.bigIdea, m.lesson, m.anchor.theme, m.inApp, ...Object.values(m.levels), ...m.benefits,
    ...m.facilitator.talkingPoints, ...m.facilitator.discussionPrompts, m.facilitator.howToRun,
    ...m.quiz.questions.flatMap((q) => [q.q, q.explain, ...q.options])].join(' ').replace(/"[^"]*"/g, ' ');
};

describe('L144 — present, whole, and inside the authored floors', () => {
  it('exists in source and in the live array', () => {
    expect(start).toBeGreaterThan(-1);
    expect(mod()).toBeTruthy();
  });
  it('the painted lesson count matches the real one', () => {
    expect(LIVING_LESSONS_META.weeks).toBe(LIVING_LESSONS_MODULES.length);
  });
  it('carries the authored floors', () => {
    const m = mod();
    expect(m.quiz.questions.length).toBeGreaterThanOrEqual(10);
    expect(m.benefits.length).toBeGreaterThanOrEqual(10);
    expect(m.facilitator.talkingPoints.length).toBeGreaterThanOrEqual(10);
    expect(m.facilitator.discussionPrompts.length).toBeGreaterThanOrEqual(10);
    for (const ref of ['Proverbs 11:1', 'Matthew 25:15', 'Isaiah 10:1']) {
      expect(m.anchor.ref).toContain(ref);
    }
  });
  it('every quiz question is answerable and explained', () => {
    for (const q of mod().quiz.questions) {
      expect(q.options.length).toBeGreaterThanOrEqual(3);
      expect(q.answer).toBeGreaterThanOrEqual(0);
      expect(q.answer).toBeLessThan(q.options.length);
      expect(q.explain.length).toBeGreaterThan(40);
    }
  });
  it('every age band resolves to real authored prose', () => {
    for (const band of AGE_BANDS) {
      expect(resolveForAge(mod(), band.id).text.length, band.id).toBeGreaterThan(400);
    }
  });
});

describe('L144 — every quoted span is verbatim KJV', () => {
  it('quotation marks are balanced', () => {
    expect(quotedSpans(withoutStories(l)).balanced).toBe(true);
  });
  it('the lesson quotes Scripture heavily (not vacuously few spans)', () => {
    expect(quotedSpans(withoutStories(l)).spans.length).toBeGreaterThan(35);
  });
  it('EVERY double-quoted span appears letter-for-letter in the KJV corpus', () => {
    const bad = [];
    for (const span of quotedSpans(withoutStories(l)).spans) {
      for (const piece of span.split('...')) {
        const p = piece.trim();
        if (p && !inKjv(p)) bad.push(p.slice(0, 120));
      }
    }
    expect(bad, `not verbatim KJV:\n  ${bad.join('\n  ')}`).toEqual([]);
  });
  it('the stories carry a verse and are substantial', () => {
    for (const s of mod().stories) {
      expect(s.body.length).toBeGreaterThan(800);
      expect(s.verse).toMatch(/^[0-9A-Za-z ]+ \d+:\d+$/);
    }
    // One imagined parable and one account of real lived experience. The
    // testimony must NOT be labelled a parable — it is other men's lives.
    expect(mod().stories.map((s) => s.kind).sort()).toEqual(['parable', 'testimony']);
    // And the testimony must say WHOSE account it is and what kind of account
    // it is. A composite pattern presented as one named man's documented case
    // would be a small lie told for effect (DR-0215/DR-0076).
    const t = mod().stories.find((s) => s.kind === 'testimony');
    expect(t.source, 'a testimony claims a real event and must be attributed').toBeTruthy();
    expect(t.source).toMatch(/Darrell/);
    expect(t.source, 'it must say it is a reported pattern, not one named case').toMatch(/rather than as one named person|recurring account/i);
    // The parable must NOT carry a source — it claims nothing real.
    expect(mod().stories.find((s) => s.kind === 'parable').source).toBeUndefined();
  });
});

describe('L144 — the typography this house is bound to', () => {
  it('names Yahweh in our voice and never the generic term', () => {
    const ours = ourVoice();
    expect((ours.match(/Yahweh/g) || []).length).toBeGreaterThan(5);
    expect(ours).not.toMatch(/\bGod\b/);
  });
  it('never capitalizes the adversary', () => {
    expect(ourVoice()).not.toMatch(/Satan|Lucifer/);
  });
});

describe('L144 — the false balance is the spine, and it is classed as worship', () => {
  it('the rigged scale is named an abomination, not an inefficiency', () => {
    expect(verse('Proverbs', 11, 1)).toBe('A false balance is abomination to the LORD: but a just weight is his delight.');
    expect(l).toContain('A false balance is abomination to the LORD');
  });
  it('two standards in one bag are forbidden outright', () => {
    expect(verse('Deuteronomy', 25, 13)).toContain('Thou shalt not have in thy bag divers weights');
    expect(l).toContain('Thou shalt not have in thy bag divers weights, a great and a small');
  });
  it('the NATIONAL outcome is attached to the honest weight — Darrell’s growth claim, in the text', () => {
    expect(verse('Deuteronomy', 25, 15)).toContain('that thy days may be lengthened in the land');
    expect(l).toContain('that thy days may be lengthened in the land');
  });
  it('ABILITY is the allocation standard Heaven uses', () => {
    expect(verse('Matthew', 25, 15)).toContain('to every man according to his several ability');
    expect(l).toContain('to every man according to his several ability');
  });
  it('the economic thesis verse is kept — the field was productive', () => {
    expect(verse('Proverbs', 13, 23)).toBe('Much food is in the tillage of the poor: but there is that is destroyed for want of judgment.');
    expect(l).toContain('Much food is in the tillage of the poor');
    expect(l).toContain('destroyed for want of judgment');
  });
});

describe('L144 — the documented record stays documented (DR-0100 tier one)', () => {
  it('keeps the measured evidence rather than a vague gesture at unfairness', () => {
    for (const fact of ['Federal Reserve', 'Small Business Credit Survey', 'Matched-pair', 'matched-pair', 'Citigroup']) {
      if (fact === 'Matched-pair' || fact === 'matched-pair') continue;
      expect(l, `the lesson must keep the ${fact} evidence`).toContain(fact);
    }
    expect(/matched-pair/i.test(l), 'matched-pair testing is the evidence that removes the usual counter-argument').toBe(true);
  });
  it('keeps the jobs figure, which is what connects capital denial to needing work', () => {
    // Darrell: "they needed the children to need jobs so they undermine".
    // The jobs that were never created are the mechanism, and dropping the
    // number would leave the claim floating.
    expect(/six million jobs|jobs that were never created/i.test(l)).toBe(true);
  });
  it('keeps the enforcement findings as FIGURES, which is how they stay honest', () => {
    for (const fact of ['1071', '1,809', '159']) {
      expect(l, `the lesson must keep the ${fact} figure`).toContain(fact);
    }
  });
  it('names the written kind of injustice, because that is what a map or a rule is', () => {
    expect(verse('Isaiah', 10, 1)).toContain('that write grievousness which they have prescribed');
    expect(l).toContain('that write grievousness which they have prescribed');
    expect(verse('Isaiah', 10, 2)).toContain('To turn aside the needy from judgment');
    expect(l).toContain('To turn aside the needy from judgment');
  });
});

describe('L144 — THE CORRECTION, pinned hardest because it is the likeliest to be softened', () => {
  // Darrell said he believed the immigrant-lending claim fully, AND asked for it
  // to be researched rather than agreed with. The honest finding is that the
  // disparity is real but the mechanism is usually NOT bank preference. A later
  // edit that quietly restores simple agreement would break the very discipline
  // he asked for, so every half of it is asserted.
  it('does NOT claim banks favour immigrants for those neighbourhoods', () => {
    expect(l).toMatch(/mechanism, however, is generally not the bank|mechanism is generally not that banks/i);
  });
  it('names the actual documented channel, which bypasses banks', () => {
    for (const word of ['rotating credit associations', 'kye', 'hui', 'esusu']) {
      expect(l, `the lesson must name ${word}`).toContain(word);
    }
    expect(l).toMatch(/bypass|route around/i);
  });
  it('keeps the half of his claim that IS documented — the disparity stands', () => {
    expect(l).toMatch(/disparity he describes is real and documented|that half stands/i);
  });
  it('keeps the turn that makes the correction good news rather than a rebuke', () => {
    // esusu is West African and came with enslaved Africans: an interrupted
    // inheritance, not somebody else's advantage. Losing this sentence turns a
    // key back into a grievance.
    expect(l).toMatch(/Yoruba/);
    expect(l).toMatch(/enslaved Africans/);
    expect(l).toMatch(/inheritance/i);
  });
  it('records that he ASKED for it to be checked — the discipline is the teaching', () => {
    expect(l).toMatch(/researched rather than agreed with|checked rather than repeated/i);
  });
  it('keeps his own mid-stream refinement rather than the broader first version', () => {
    // He narrowed it himself: not every company, but in every industry the
    // voices are not heard. The narrower claim is the one that survives.
    expect(l).toMatch(/not every company/i);
    expect(l).toMatch(/voices are not being heard|voices are not heard/i);
  });
});

describe('L144 — the record of erasure, told to its actual end', () => {
  it('names the executive order and the court order by their real particulars', () => {
    expect(l).toContain('14253');
    expect(l).toMatch(/Angel Kelley/);
    expect(l).toMatch(/twenty-one days|21 days/);
  });
  it('keeps the panel swap, which is the whole device', () => {
    // The replacement panel is not false. That is the point: quote accurately,
    // drop the clause — the same method L142 exhibits from Psalm 91.
    expect(l).toMatch(/The Dirty Business of Slavery/);
    expect(l).toMatch(/Celebrating Independence Throughout the Years/);
    expect(l).toMatch(/Nothing on that new panel is false/);
  });
  it('Scripture is cited on removing markers, literally', () => {
    expect(verse('Proverbs', 22, 28)).toBe('Remove not the ancient landmark, which thy fathers have set.');
    expect(l).toContain('Remove not the ancient landmark, which thy fathers have set');
    expect(verse('Deuteronomy', 27, 17)).toContain('Cursed be he that removeth his neighbour’s landmark');
    expect(l).toContain('Cursed be he that removeth his neighbour’s landmark');
    // The one that binds the marker to the field and to the Redeemer.
    expect(verse('Proverbs', 23, 11)).toContain('their redeemer is mighty; he shall plead their cause with thee');
    expect(l).toContain('their redeemer is mighty; he shall plead their cause with thee');
  });

  // THE TWO HONESTY CONSTRAINTS. Both cut against the lesson's own argument,
  // and both are the first things a later edit would be tempted to remove.
  it('tells the Wilcox case to its ACTUAL end, including the ruling that went against her', () => {
    expect(l).toMatch(/UPHELD it|upheld the removal/);
    expect(l).toMatch(/The courts did not vindicate her/);
    // Quoting only the favourable first ruling is precisely the clause-dropping
    // device this lesson condemns, so doing it here would be self-refuting.
    expect(l).toMatch(/would be doing the very thing this lesson is against/);
  });
  it('states the distribution of harm WITHOUT asserting a proven motive', () => {
    expect(l).toMatch(/They do not by themselves establish WHY/);
    expect(l).toMatch(/not a proven motive/);
    // And it must still refuse to soften the measured fact into nothing.
    expect(l).toMatch(/needs no motive to be a fact worth naming/);
  });
  it('includes the other side’s stated position rather than omitting it', () => {
    expect(l).toMatch(/performance and competence rather than race/);
    expect(l).toMatch(/belongs in the record here rather than being left out/);
  });
});

describe('L144 — it ends on the two ways, because the evidence was never the lesson', () => {
  // Darrell, correcting the lesson mid-build: the point is the evil will and
  // that what they are doing is against the Lord's will — and there are two
  // ways according to the Word. Without this the lesson is a political brief.
  it('says outright that the documented material is evidence, not the lesson', () => {
    expect(l).toMatch(/It is EVIDENCE|the evidence was never the lesson/i);
    expect(l).toMatch(/which of two ways is being walked/i);
  });
  it('sets the two ways from the Word rather than as a figure of speech', () => {
    expect(verse('Deuteronomy', 30, 15)).toBe('See, I have set before thee this day life and good, and death and evil;');
    expect(l).toContain('See, I have set before thee this day life and good, and death and evil');
    expect(verse('Jeremiah', 21, 8)).toContain('I set before you the way of life, and the way of death');
    expect(l).toContain('I set before you the way of life, and the way of death');
    expect(verse('Matthew', 7, 14)).toContain('strait is the gate, and narrow is the way');
    expect(l).toContain('strait is the gate, and narrow is the way');
  });
  it('warns about the way that does not feel like one — the merchant with a margin', () => {
    expect(verse('Proverbs', 14, 12)).toBe('There is a way which seemeth right unto a man, but the end thereof are the ways of death.');
    expect(l).toContain('There is a way which seemeth right unto a man');
    expect(l).toMatch(/felt like a man with a margin/);
  });
  it('names the renaming by its own verse', () => {
    expect(verse('Isaiah', 5, 20)).toContain('that put bitter for sweet, and sweet for bitter');
    expect(l).toContain('that put bitter for sweet, and sweet for bitter');
  });
  it('answers the removed markers with the One who keeps the record', () => {
    expect(verse('Deuteronomy', 30, 19)).toContain('I call heaven and earth to record this day against you');
    expect(l).toContain('I call heaven and earth to record this day against you');
    expect(l).toMatch(/erasure is not working where it counts/i);
  });
  it('ends in a CHOICE offered to everyone present, not a verdict on some of them', () => {
    // A room that leaves accused will not act. This is the difference between
    // a lesson and an indictment, and it is the thing most easily lost.
    expect(l).toMatch(/choose you this day whom ye will serve/);
    expect(l).toMatch(/including those who voted for what is described here/i);
    expect(mod().facilitator.talkingPoints.join(' ')).toMatch(/leaves accused will not act/i);
  });
});

describe('L144 — the remedy has arithmetic, and vengeance stays where it belongs', () => {
  it('Nehemiah required restoration the same day, itemised', () => {
    expect(verse('Nehemiah', 5, 7)).toContain('Ye exact usury, every one of his brother');
    expect(l).toContain('Ye exact usury, every one of his brother');
    expect(verse('Nehemiah', 5, 11)).toContain('Restore, I pray you, to them, even this day');
    expect(l).toContain('Restore, I pray you, to them, even this day');
  });
  it('vengeance is left with Yahweh — Darrell said so himself', () => {
    expect(verse('Romans', 12, 19)).toContain('Vengeance is mine; I will repay, saith the Lord');
    expect(l).toContain('Vengeance is mine; I will repay, saith the Lord');
  });
  it('and speech is still commanded, so the posture is not silence', () => {
    expect(verse('Proverbs', 31, 9)).toContain('plead the cause of the poor and needy');
    expect(l).toContain('plead the cause of the poor and needy');
  });
  it('ends on the instrument rather than the grievance', () => {
    const m = mod();
    expect(m.inApp).toMatch(/pooled hand|pool/i);
    expect(m.facilitator.howToRun).toMatch(/last ten minutes belong to the instrument/i);
  });
});
