-- =============================================================================
-- 0013 — COLG sermon-history backfill from @thelovecorner (generated 2026-06-14)
-- =============================================================================
-- BG's historical messages (Sundays + Wednesday Bible Study) sourced as LINKS
-- (metadata only, no downloads) and parsed from the channel video titles by
-- scripts/choir-youtube-backfill.mjs (shared parser app/src/lib/youtube-title-parse.js).
-- 125 of 335 videos carried a parseable date; the rest are undated clips/special
-- events and are left for manual entry. Targets the church instance by slug
-- ('colg', seeded by 0012) so no instance_id is needed. Idempotent: ON CONFLICT
-- (instance_id, video_id) DO NOTHING, so re-running the lane never duplicates.
-- Runs after 0011 (table) + 0012 (instance). source=youtube; review/edit in-app.
-- =============================================================================

INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '_f0sVWTrNgw', 'https://www.youtube.com/watch?v=_f0sVWTrNgw', '2026-06-10', 'sunday', 'LET GO AND LET GOD HELP YOU', 'Bishop E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Nj-63jW1WY4', 'https://www.youtube.com/watch?v=Nj-63jW1WY4', '2026-06-03', 'wednesday', 'THANK YOU FOR THE REMINDER!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'I_uiVEuU9hI', 'https://www.youtube.com/watch?v=I_uiVEuU9hI', '2026-05-27', 'wednesday', 'GOD IS AFTER YOUR EAR TO MAKE HIS PURPOSE CLEAR!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Du-BLBHO8tE', 'https://www.youtube.com/watch?v=Du-BLBHO8tE', '2026-05-20', 'wednesday', 'YOU WERE BUILT TO WIN!', 'Bishop Lloyd E.Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Npp9dkt1XC0', 'https://www.youtube.com/watch?v=Npp9dkt1XC0', '2026-05-13', 'wednesday', 'I', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ol5wKnBINpU', 'https://www.youtube.com/watch?v=ol5wKnBINpU', '2026-05-06', 'wednesday', 'NEED ANSWERS, WATCH GOD TURN IT AROUND!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'uQ00hIf2YsM', 'https://www.youtube.com/watch?v=uQ00hIf2YsM', '2026-04-29', 'wednesday', 'HELP OTHERS AND TRUST GOD TO HELP YOU', 'Bishop Lloyd E Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'BHbsKQ-3_x0', 'https://www.youtube.com/watch?v=BHbsKQ-3_x0', '2026-04-22', 'wednesday', 'UNLOCK YOUR NEXT CHAPTER!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'y6rzUGleflI', 'https://www.youtube.com/watch?v=y6rzUGleflI', '2026-04-18', 'sunday', 'Roline Brumfield Homegoing Service  4 - 18 - 2026', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'JkpwSoeeX5w', 'https://www.youtube.com/watch?v=JkpwSoeeX5w', '2026-04-15', 'wednesday', '4 -15 -26 Bishop Lloyd E. Gwin Wednesday Bible Study  "IF HE CAN GET UP, I CAN TOO!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'xLhOOy1smtM', 'https://www.youtube.com/watch?v=xLhOOy1smtM', '2026-04-08', 'wednesday', 'WATCH GOD TURN IT AROUND!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'kg_XhmgxYXo', 'https://www.youtube.com/watch?v=kg_XhmgxYXo', '2026-04-01', 'wednesday', 'THE KING IS STILL HERE!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'cbEGBYks-Ms', 'https://www.youtube.com/watch?v=cbEGBYks-Ms', '2026-03-25', 'sunday', 'IF YOU WANT SOMETHING YOU NEVER HAD, DO SOMETHING YOU NEVER DONE', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '16javnubkyU', 'https://www.youtube.com/watch?v=16javnubkyU', '2026-03-18', 'wednesday', 'GOD IS PREPARING YOU FOR YOUR DESTINY', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '8Ap0rvmU9dA', 'https://www.youtube.com/watch?v=8Ap0rvmU9dA', '2026-03-11', 'wednesday', '3 - 11- 26 Bishop Lloyd E. Gwin Wednesday Bible Study "ONLY MOVE WHEN HE MOVES!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'AyiDcYOnkRs', 'https://www.youtube.com/watch?v=AyiDcYOnkRs', '2026-03-04', 'wednesday', 'YOU CAN', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '34tdYenmT-A', 'https://www.youtube.com/watch?v=34tdYenmT-A', '2026-02-25', 'wednesday', '2- 25 - 26 Bishop Lloyd E. Gwin Wednesday Bible Study " NOW IS THE TIME!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'zWgMNShU5as', 'https://www.youtube.com/watch?v=zWgMNShU5as', '2026-02-18', 'wednesday', 'I LOVE YOU ... I SEE YOU!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'gu6Oa67VpmI', 'https://www.youtube.com/watch?v=gu6Oa67VpmI', '2026-02-11', 'wednesday', 'I WANT TO LOVE LIKE HIM!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'GzCdILHckwQ', 'https://www.youtube.com/watch?v=GzCdILHckwQ', '2026-02-04', 'wednesday', 'You Will Make It To The Other Side', 'Bishop Lloyd E . Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'SxS0xrZHWxw', 'https://www.youtube.com/watch?v=SxS0xrZHWxw', '2026-01-28', 'wednesday', 'DON', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'fGgEm6Mhk8g', 'https://www.youtube.com/watch?v=fGgEm6Mhk8g', '2026-01-21', 'wednesday', 'YOU', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'rHd2QpBctfE', 'https://www.youtube.com/watch?v=rHd2QpBctfE', '2026-01-14', 'wednesday', 'FAITH, THE FINAL FRONTIER!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '6j0ToFoBNxw', 'https://www.youtube.com/watch?v=6j0ToFoBNxw', '2026-01-07', 'wednesday', 'JESUS CAN FIX IT!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '7lBdy6xjdQg', 'https://www.youtube.com/watch?v=7lBdy6xjdQg', '2025-12-24', 'wednesday', 'We', 'Bishop Lloyd E.Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '76fT-J4AKec', 'https://www.youtube.com/watch?v=76fT-J4AKec', '2025-12-17', 'wednesday', 'YOU', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ZxKOhlajHpU', 'https://www.youtube.com/watch?v=ZxKOhlajHpU', '2025-12-10', 'wednesday', 'GET OFF THE FENCE!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'HMqG4aQMBR4', 'https://www.youtube.com/watch?v=HMqG4aQMBR4', '2025-12-03', 'sunday', 'DON', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'hghmd8HLNHg', 'https://www.youtube.com/watch?v=hghmd8HLNHg', '2025-11-26', 'sunday', 'REMEMBERING THE  GOODNESS OF GOD', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'wdptLNDt9Hs', 'https://www.youtube.com/watch?v=wdptLNDt9Hs', '2025-11-19', 'wednesday', 'I BUILD MY LIFE WITH THE WORD OF GOD!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'RTuZZN-i0dg', 'https://www.youtube.com/watch?v=RTuZZN-i0dg', '2025-11-12', 'wednesday', 'SHOUT- THE VICTORY BELONGS TO GOD', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Mfp79c7RuTE', 'https://www.youtube.com/watch?v=Mfp79c7RuTE', '2025-11-05', 'wednesday', 'IT', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'pLRg9sY8_V8', 'https://www.youtube.com/watch?v=pLRg9sY8_V8', '2025-08-13', 'wednesday', 'FOLLOW ME AS I FOLLOW CHRIST!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '3uTCLb1e_SM', 'https://www.youtube.com/watch?v=3uTCLb1e_SM', '2025-08-06', 'wednesday', 'DARE TO TRY AND DON', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'SDkCaxKzjkU', 'https://www.youtube.com/watch?v=SDkCaxKzjkU', '2025-07-30', 'wednesday', 'SEEK GOD FIRST AND FINISH THE RACE!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'rq6M6K9Pe3w', 'https://www.youtube.com/watch?v=rq6M6K9Pe3w', '2025-07-23', 'sunday', 'JUST DO IT!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'pfXKXFN5-3g', 'https://www.youtube.com/watch?v=pfXKXFN5-3g', '2025-07-16', 'wednesday', 'ATTACK ALL ENEMIES AS YOU LEVEL UP', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'EmbWeBVGfbY', 'https://www.youtube.com/watch?v=EmbWeBVGfbY', '2025-07-02', 'wednesday', 'Mixed Company!', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '962M48q8W2o', 'https://www.youtube.com/watch?v=962M48q8W2o', '2025-06-25', 'wednesday', 'It', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'RTMEQjm7x84', 'https://www.youtube.com/watch?v=RTMEQjm7x84', '2025-06-18', 'wednesday', '6 -18 - 2025 BISHOP LLOYD GWIN! WEDNESDAY BIBLE STUDY! GET READY AND STAY READY - A STORM IS COMING!', 'BISHOP LLOYD GWIN', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'av4Rxx0CHMo', 'https://www.youtube.com/watch?v=av4Rxx0CHMo', '2025-06-11', 'wednesday', 'CHILDREN CAN HELP!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'CNtfOJku9yE', 'https://www.youtube.com/watch?v=CNtfOJku9yE', '2025-06-04', 'wednesday', 'I', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '_WsYVC72YaY', 'https://www.youtube.com/watch?v=_WsYVC72YaY', '2025-05-28', 'wednesday', '5 - 28 - 2025 Bishop Lloyd E. Gwin  Wednesday Bible Study "KEEP THE FIRE BURNING!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Wda9oYfM7P8', 'https://www.youtube.com/watch?v=Wda9oYfM7P8', '2025-05-21', 'wednesday', 'A FRESH START', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'fL_3U7FG91E', 'https://www.youtube.com/watch?v=fL_3U7FG91E', '2025-05-14', 'wednesday', 'God Sees You!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '_vb8ucnwi1g', 'https://www.youtube.com/watch?v=_vb8ucnwi1g', '2025-05-07', 'wednesday', 'HE', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'YAUsHgaoAR8', 'https://www.youtube.com/watch?v=YAUsHgaoAR8', '2025-04-30', 'wednesday', 'DON', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'v8VbUay8Lmc', 'https://www.youtube.com/watch?v=v8VbUay8Lmc', '2025-04-23', 'wednesday', 'I KNOW WHO I AM IN GOD', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ElzaP_DbeJs', 'https://www.youtube.com/watch?v=ElzaP_DbeJs', '2025-04-16', 'wednesday', 'PATIENT IS A VIRTUE', 'Bishop Lloyd E . Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '3-vMut7cjgM', 'https://www.youtube.com/watch?v=3-vMut7cjgM', '2025-04-09', 'wednesday', 'GOD IS IN CONTROL', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '-qV5lWL1YJA', 'https://www.youtube.com/watch?v=-qV5lWL1YJA', '2025-04-02', 'wednesday', 'JESUS LOVES ME!', 'Bishop Lloyd E Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '7EB28PcGCs4', 'https://www.youtube.com/watch?v=7EB28PcGCs4', '2025-03-26', 'wednesday', 'YOU CAN', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '-0KdLHtM4Ns', 'https://www.youtube.com/watch?v=-0KdLHtM4Ns', '2025-03-19', 'wednesday', 'IT', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'p93gbKvUBwg', 'https://www.youtube.com/watch?v=p93gbKvUBwg', '2025-03-12', 'wednesday', 'YOU ARE SOUGHT OUT TO BE SAVED', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'QwM9QBXqMPc', 'https://www.youtube.com/watch?v=QwM9QBXqMPc', '2025-03-05', 'wednesday', 'SOMEBODY IS GOING TO GET SAVED', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'yAMBLbi0MqQ', 'https://www.youtube.com/watch?v=yAMBLbi0MqQ', '2025-02-26', 'wednesday', 'MY IF ONLY HAS BEEN SETTLED!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'PkEBTRKP_es', 'https://www.youtube.com/watch?v=PkEBTRKP_es', '2025-02-19', 'sunday', '2-19-25 Sister Jasmine Johnson  Setting Up The Moment', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Kl46PEdEwBE', 'https://www.youtube.com/watch?v=Kl46PEdEwBE', '2025-02-05', 'wednesday', 'Keep Working Your Change Is Going To Come!', 'Bishop Lloyd E Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '4czeGi4AFNY', 'https://www.youtube.com/watch?v=4czeGi4AFNY', '2025-01-29', 'wednesday', 'New Expectation New Attitude!', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '_TuidCXY7wI', 'https://www.youtube.com/watch?v=_TuidCXY7wI', '2025-01-22', 'wednesday', 'Do The Right Thing', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'MMEEXwUgwbE', 'https://www.youtube.com/watch?v=MMEEXwUgwbE', '2025-01-15', 'wednesday', 'NEW YEAR ,NEW ME!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'o6g0yoI7a7Y', 'https://www.youtube.com/watch?v=o6g0yoI7a7Y', '2025-01-08', 'wednesday', 'New Year! New Praise!', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'jYrx9DrTAsk', 'https://www.youtube.com/watch?v=jYrx9DrTAsk', '2024-12-24', 'wednesday', 'PUT THE  MESS TO REST', 'Bishop Lloyd E .Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '8YbYUhEBETk', 'https://www.youtube.com/watch?v=8YbYUhEBETk', '2024-12-18', 'wednesday', 'BUILD ON A SOLID FOUNDATION', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'y6SXdTavUvI', 'https://www.youtube.com/watch?v=y6SXdTavUvI', '2024-12-11', 'wednesday', 'Restore Me!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '8U681UpohQM', 'https://www.youtube.com/watch?v=8U681UpohQM', '2024-12-04', 'wednesday', 'Before  You Leave Home!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'AgBDQ99zfHE', 'https://www.youtube.com/watch?v=AgBDQ99zfHE', '2024-11-27', 'wednesday', 'GIVE GOD A LOUD PRAISE!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'AzYDFtQoxM8', 'https://www.youtube.com/watch?v=AzYDFtQoxM8', '2024-11-20', 'wednesday', 'IT IS RESET TIME!', 'BISHOP LLOYD GWIN', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'd_BPAZEgqSo', 'https://www.youtube.com/watch?v=d_BPAZEgqSo', '2024-11-13', 'wednesday', 'GET READY TO SHOUT', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'VLoMrlpzObw', 'https://www.youtube.com/watch?v=VLoMrlpzObw', '2024-11-06', 'wednesday', 'GOD IS COUNTING ON US AND WE CAN COUNT ON HIM!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'uYkixcW7crI', 'https://www.youtube.com/watch?v=uYkixcW7crI', '2024-10-30', 'sunday', 'Ship Wrecked', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '4ltGtcUIJvM', 'https://www.youtube.com/watch?v=4ltGtcUIJvM', '2024-10-23', 'sunday', 'He Is Counting On Us', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'E7ReoB72O7Q', 'https://www.youtube.com/watch?v=E7ReoB72O7Q', '2024-10-16', 'wednesday', 'I AM PREFERED!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'XNGd0lcTpw0', 'https://www.youtube.com/watch?v=XNGd0lcTpw0', '2024-10-09', 'sunday', 'Endurance', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Zg6jBQA0ATM', 'https://www.youtube.com/watch?v=Zg6jBQA0ATM', '2024-10-02', 'wednesday', 'GIVE IT UP!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ga4UuIMczpc', 'https://www.youtube.com/watch?v=ga4UuIMczpc', '2024-09-25', 'wednesday', 'BLESSED AND HIGHLY FAVORED!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '3rcOBlNX06k', 'https://www.youtube.com/watch?v=3rcOBlNX06k', '2024-09-18', 'wednesday', 'You can always Come Home', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'KN-a-wSslyc', 'https://www.youtube.com/watch?v=KN-a-wSslyc', '2024-09-11', 'wednesday', '9 11 2024 Sister Jasmine Johnson Wednesday Bible Study', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'nJZB-IyR08w', 'https://www.youtube.com/watch?v=nJZB-IyR08w', '2024-09-04', 'wednesday', 'WE', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'X4rNsAdnWCs', 'https://www.youtube.com/watch?v=X4rNsAdnWCs', '2024-09-01', 'sunday', 'We', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'PRaoeIU0zNs', 'https://www.youtube.com/watch?v=PRaoeIU0zNs', '2024-08-28', 'wednesday', 'RESTORATION', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'raQFlzm5cAY', 'https://www.youtube.com/watch?v=raQFlzm5cAY', '2024-08-21', 'wednesday', 'IT', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'WZvpLiusbyQ', 'https://www.youtube.com/watch?v=WZvpLiusbyQ', '2024-08-14', 'wednesday', 'It', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'jNyt0iYjZZ4', 'https://www.youtube.com/watch?v=jNyt0iYjZZ4', '2024-08-07', 'wednesday', 'Anything Jesus Touches He Changes!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'K4aApPpCIPU', 'https://www.youtube.com/watch?v=K4aApPpCIPU', '2024-07-31', 'wednesday', '7 31 24 Bishop Lloyd Gwin Wednesday Bible Study  Don''t Ever  Give Up!', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '8NWmw9KERCE', 'https://www.youtube.com/watch?v=8NWmw9KERCE', '2024-07-21', 'wednesday', 'WAIT ON GOD!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '6U3gawNK7Yg', 'https://www.youtube.com/watch?v=6U3gawNK7Yg', '2024-07-17', 'wednesday', 'LIVING FOR CHRIST', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'UTPGRuoQER0', 'https://www.youtube.com/watch?v=UTPGRuoQER0', '2024-07-03', 'wednesday', 'There Is No God Like Our God', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'gyRig7MQMx8', 'https://www.youtube.com/watch?v=gyRig7MQMx8', '2024-06-23', 'sunday', 'Save Your House', 'Bishop Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'AwDrGx8CyE0', 'https://www.youtube.com/watch?v=AwDrGx8CyE0', '2024-06-26', 'wednesday', 'SAVE YOUR HOUSE!!!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'F0U6bvcDJbY', 'https://www.youtube.com/watch?v=F0U6bvcDJbY', '2024-06-19', 'wednesday', 'Watch Him Deliver You', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'EA7Rz9zheEE', 'https://www.youtube.com/watch?v=EA7Rz9zheEE', '2024-06-12', 'wednesday', 'You Never Know Who Is Watching', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'TN1h3p5yU68', 'https://www.youtube.com/watch?v=TN1h3p5yU68', '2024-06-05', 'wednesday', 'GOD IS ALWAYS THERE', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'VvpAQ-VjRQs', 'https://www.youtube.com/watch?v=VvpAQ-VjRQs', '2024-05-29', 'wednesday', 'I Knew It Would Happen', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'PPNUWAXZbbs', 'https://www.youtube.com/watch?v=PPNUWAXZbbs', '2024-05-22', 'wednesday', 'Watch God Do What Only He Can Do!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'WYXr99gkkdg', 'https://www.youtube.com/watch?v=WYXr99gkkdg', '2024-05-15', 'wednesday', 'God didn', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'WgFW0LX8PCI', 'https://www.youtube.com/watch?v=WgFW0LX8PCI', '2024-05-12', 'sunday', 'GOD DIDN', 'BISHOP LLOYD GWIN', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'JGeycYaO8vI', 'https://www.youtube.com/watch?v=JGeycYaO8vI', '2024-05-08', 'wednesday', 'A Blessing from God', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'IQdi2Woq-fE', 'https://www.youtube.com/watch?v=IQdi2Woq-fE', '2024-05-01', 'wednesday', 'Deliver Us From HOW!', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'FrVT5-_Lsy4', 'https://www.youtube.com/watch?v=FrVT5-_Lsy4', '2024-04-24', 'sunday', '4 24 24 Message Give God Your Best and Then Trust Him To Do The Rest', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Km8v4MRfeLk', 'https://www.youtube.com/watch?v=Km8v4MRfeLk', '2024-04-21', 'sunday', '4-21-2024 Bishop Gwin Give God Your Best and Then Trust Him To Do The Rest', 'Bishop Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '3znlzLX0mII', 'https://www.youtube.com/watch?v=3znlzLX0mII', '2024-04-17', 'wednesday', 'Stand Strong', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Zcn4ADVsGdM', 'https://www.youtube.com/watch?v=Zcn4ADVsGdM', '2024-04-07', 'sunday', 'Everything Is Not A Good Thing', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'zQ2zNw9vFBU', 'https://www.youtube.com/watch?v=zQ2zNw9vFBU', '2024-04-10', 'wednesday', '4 10 24 Wednesday Bible Study Everything Is Not A Good Thing', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'xqZi6AUegPw', 'https://www.youtube.com/watch?v=xqZi6AUegPw', '2024-04-03', 'wednesday', '4 3 24 Wednesday Bible Study GOD LOVES ME !', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'GjhJu1e8OVI', 'https://www.youtube.com/watch?v=GjhJu1e8OVI', '2024-03-31', 'sunday', '3/31/24 Easter 2024 "GOD LOVES ME', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'QrE-3k2DHmc', 'https://www.youtube.com/watch?v=QrE-3k2DHmc', '2024-03-24', 'sunday', '3 24 24 DO WHAT HE TELLS YOU TO DO', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'H5ve4V2Ay_s', 'https://www.youtube.com/watch?v=H5ve4V2Ay_s', '2024-03-27', 'wednesday', 'DO WHAT HE TELLS YOU TO DO', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ThF_ZLJPKTM', 'https://www.youtube.com/watch?v=ThF_ZLJPKTM', '2024-03-20', 'wednesday', '3 20 2024 Wednesday Bible Study  GROW UP IN GOD', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'wrmM6JUq9mg', 'https://www.youtube.com/watch?v=wrmM6JUq9mg', '2024-03-17', 'sunday', '3 17 2024  Bishop Gwin  GROW UP IN GOD', 'Bishop Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'YWYr7byxiXw', 'https://www.youtube.com/watch?v=YWYr7byxiXw', '2024-03-03', 'sunday', 'We', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'mCXmnCAjUog', 'https://www.youtube.com/watch?v=mCXmnCAjUog', '2024-03-13', 'wednesday', 'PETER AND THE CHURCH  SHEPHERDS AND SHEEP!', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '_3xrEw8YUTU', 'https://www.youtube.com/watch?v=_3xrEw8YUTU', '2024-02-28', 'sunday', '2/28/2024 Black History Month Jasmine Johnson', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'raBon8_qol0', 'https://www.youtube.com/watch?v=raBon8_qol0', '2024-03-06', 'wednesday', 'We', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'ZU9BlxfB7NQ', 'https://www.youtube.com/watch?v=ZU9BlxfB7NQ', '2024-02-28', 'wednesday', 'The Best Is Yet To Come', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), '4-3pcua7x3s', 'https://www.youtube.com/watch?v=4-3pcua7x3s', '2024-02-21', 'wednesday', 'Know The Past, Shape The Future', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'SwOPeeLGQqw', 'https://www.youtube.com/watch?v=SwOPeeLGQqw', '2024-02-14', 'wednesday', '2/14/2024  Wednesday Bible Study  THANK YOU FOR LETTING THE LORD USE YOU', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'D_V5IKs0byc', 'https://www.youtube.com/watch?v=D_V5IKs0byc', '2024-02-07', 'wednesday', 'Your Victory is Guaranteed', 'Bishop Lloyd Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'kP8vj9sAL8g', 'https://www.youtube.com/watch?v=kP8vj9sAL8g', '2024-01-31', 'wednesday', 'WHEN IT HAPPEN', 'Bishop Lloyd E. Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Y41SOaCKO1g', 'https://www.youtube.com/watch?v=Y41SOaCKO1g', '2024-01-24', 'wednesday', 'It', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'l68G7MxnYG4', 'https://www.youtube.com/watch?v=l68G7MxnYG4', '2024-01-10', 'wednesday', '1 10 2024 Wednesday Bible Study  Lord You Can Expect More In 2024', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'GTg8nVB-sr8', 'https://www.youtube.com/watch?v=GTg8nVB-sr8', '2024-01-03', 'wednesday', '01 03 24 Wednesday Bible Study  Bishop Gwin There Is No god  Like Our God!', 'Bishop Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'k9c2RXw6GWU', 'https://www.youtube.com/watch?v=k9c2RXw6GWU', '2023-12-27', 'wednesday', '12 27 2023 Wednesday Bible Study  Bishop Gwin  Where He Leads Us We Will Follow', 'Bishop Gwin', 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'Sry2w3AwigE', 'https://www.youtube.com/watch?v=Sry2w3AwigE', '2023-12-20', 'wednesday', '12 20 2023 Bible Study AP Harden', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;
INSERT INTO choir_sermons (instance_id, video_id, youtube_url, service_date, service_type, title, speaker, source) VALUES ((SELECT id FROM instances WHERE slug = 'colg'), 'OrYCG59pw88', 'https://www.youtube.com/watch?v=OrYCG59pw88', '2023-12-06', 'wednesday', '12 6 23 Bible Study We Have To Go For The Kingdom To Grow', NULL, 'youtube') ON CONFLICT (instance_id, video_id) WHERE video_id IS NOT NULL DO NOTHING;

NOTIFY pgrst, 'reload schema';
