// =============================================================================
// legibility-health — in-app reader for the perpetual UI/UX legibility health
// =============================================================================
// "All data has a path and a purpose." The data here is REAL: it is generated by
// scripts/legibility-guard.mjs (the per-page WCAG-2.1-AA dark-on-dark gate) from
// the actual component source, and committed to app/src/lib/legibility-health
// .json. A vitest asserts the committed JSON is byte-in-sync with a fresh scan,
// so this is never a painted number — it is the same truth the merge gate uses.
//
// This pure reader is the seam the QCHP / Quality Care Health Plan loop view
// (lane local_75dc44d5) renders in-app: total surfaces, how many pass legibility
// today, the failing-page backlog, and the ITIL-CSI framing (the backlog is the
// fix-lane queue; the gate blocks any NEW failing page, so it can only trend
// down). Kept dependency-free + null-safe so it is unit tested (DR-0076).
import HEALTH from './legibility-health.json';

export const legibilityHealth = HEALTH;

// One pass/fail line for a status strip. e.g. "93/108 surfaces legible (15 in repair)".
export function legibilitySummaryLine(h = HEALTH) {
  const s = (h && h.summary) || { pages: 0, passing: 0, trackedDebtPages: 0, regressionPages: 0 };
  const repair = s.trackedDebtPages + s.regressionPages;
  return `${s.passing}/${s.pages} surfaces legible${repair ? ` (${repair} in repair)` : ''}`;
}

// Overall health state for a KpiDot / badge. A REGRESSION (a new failing page
// that slipped the gate — should be impossible while the gate runs, but surfaced
// honestly if it ever happens) is red; tracked debt is amber; all-clear is green.
export function legibilityState(h = HEALTH) {
  const s = (h && h.summary) || {};
  if (s.regressionPages) return 'regression';
  if (s.trackedDebtPages) return 'repair';
  return 'ok';
}

// The failing-page backlog, worst first — the fix-lane queue the loop view lists.
export function legibilityBacklog(h = HEALTH) {
  return ((h && h.pages) || []).map((p) => ({
    page: p.page,
    surface: p.page.replace(/^components\//, '').replace(/\.jsx$/, ''),
    status: p.status,
    violations: p.violations,
    kinds: p.kinds || [],
  }));
}

// Percent of surfaces currently legible — the ITIL CSI trend metric (target 100).
export function legibilityScore(h = HEALTH) {
  const s = (h && h.summary) || { pages: 0, passing: 0 };
  if (!s.pages) return 100;
  return Math.round((s.passing / s.pages) * 100);
}
