// =============================================================================
// lesson-dates — the day every lesson in every course was created (DR-0687)
// =============================================================================
// Darrell 2026-09-30, looking at Learn -> "Latest lessons, every course", which
// said only one course recorded its days and 549 lessons were left out:
//   "Add all the days the lessons were created so we can have all of them in
//    each course so they can get done."
//
// The days live in lesson-dates.json, GENERATED by scripts/derive-lesson-dates.mjs
// from git: each is the UTC author day of the earliest commit that added the
// line defining the lesson (rule and exceptions: scripts/lesson-dates-core.mjs).
// Never edited by hand; CI re-derives it from full history and fails on drift.
// Living Lessons keeps its own recorded days (living-lessons-dates.js), which
// already ride on its schedule as `added`; a day already present is never
// replaced here.
//
// `added` is the one field every Learn order reads (learn-organize.js,
// lesson-order.js, LatestLessons.jsx). The cohort courses' `date` is a
// SCHEDULED class day and is never read as a creation day.
// =============================================================================
import { courses as DATED, undated as UNDATED } from './lesson-dates.json';

const ISO_DAY = /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/;

/** The recorded creation day of a lesson in a course ('YYYY-MM-DD'), or null. */
export function lessonCreatedDay(courseKey, lessonId) {
  const row = DATED[courseKey] && DATED[courseKey][lessonId];
  return Array.isArray(row) && ISO_DAY.test(row[0]) ? row[0] : null;
}

/** Why a lesson has no day, when the generator recorded a reason; null otherwise. */
export function undatedReason(courseKey, lessonId) {
  return UNDATED[`${courseKey}/${lessonId}`] || null;
}

const courseKeyOf = (c) => (c && (c.key || (c.meta && c.meta.key))) || null;

/** A schedule with each lesson's creation day as `added` (a day already there is kept). */
export function datedSchedule(courseKey, schedule) {
  const list = Array.isArray(schedule) ? schedule : [];
  let changed = false;
  const out = list.map((m) => {
    if (!m || !m.id || (typeof m.added === 'string' && ISO_DAY.test(m.added))) return m;
    const day = lessonCreatedDay(courseKey, m.id);
    if (!day) return m;
    changed = true;
    return { ...m, added: day };
  });
  return changed ? out : list;
}

/** Courses with every lesson's creation day attached; a course with nothing to add is returned as is. */
export function withLessonDates(courses) {
  return (Array.isArray(courses) ? courses : []).map((c) => {
    if (!c || !Array.isArray(c.schedule)) return c;
    const schedule = datedSchedule(courseKeyOf(c), c.schedule);
    return schedule === c.schedule ? c : { ...c, schedule };
  });
}
