// =============================================================================
// scripture-kjv — GENERATED verbatim KJV verse text (DO NOT HAND-EDIT)
// =============================================================================
// Every entry below was fetched from bible-api.com (translation=kjv, "Public
// Domain") and normalized for whitespace ONLY (wrap-newlines collapsed to single
// spaces) — never reworded. 180 references, each confirmed real by the
// fetch (a 404 would have failed this set). This file is the single source of
// VERSE TEXT; lib/scriptures.js authors the curation that references it. To change
// the set, edit the fetch list and regenerate — do not type Scripture by hand
// (DR-0076 Verification Doctrine: fetch the actual translation, never from memory).
//
// COPYRIGHT: the King James Version (1611) is public domain, so its full text is
// reproduced. Copyrighted translations are never reproduced here (see scriptures.js
// readOnline()).
// =============================================================================

export const KJV = {
  // --- Appended 2026-07-01 for the "Eternal Algorithms" study (Conditional Truth) ---
  // Fetched verbatim from bible-api.com (translation=kjv, "Public Domain"), NOT typed
  // from memory (DR-0076). Whitespace normalized only. These anchor the study's game
  // deck (belief-vs-action) so every card resolves to real KJV text via scripture-link.
  "John 14:15": "If ye love me, keep my commandments.",
  "James 1:22": "But be ye doers of the word, and not hearers only, deceiving your own selves.",
  "Luke 6:46": "And why call ye me, Lord, Lord, and do not the things which I say?",
  "Deuteronomy 30:19": "I call heaven and earth to record this day against you, that I have set before you life and death, blessing and cursing: therefore choose life, that both thou and thy seed may live:",
  "2 Corinthians 13:5": "Examine yourselves, whether ye be in the faith; prove your own selves. Know ye not your own selves, how that Jesus Christ is in you, except ye be reprobates?",
  "John 18:37": "Pilate therefore said unto him, Art thou a king then? Jesus answered, Thou sayest that I am a king. To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth. Every one that is of the truth heareth my voice.",
  "John 18:38": "Pilate saith unto him, What is truth? And when he had said this, he went out again unto the Jews, and saith unto them, I find in him no fault at all.",
  "Psalm 103:13-14": "Like as a father pitieth his children, so the LORD pitieth them that fear him. For he knoweth our frame; he remembereth that we are dust.",
  "Deuteronomy 11:26-28": "Behold, I set before you this day a blessing and a curse; A blessing, if ye obey the commandments of the LORD your God, which I command you this day: And a curse, if ye will not obey the commandments of the LORD your God, but turn aside out of the way which I command you this day, to go after other gods, which ye have not known.",
  "James 1:23-24": "For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass: For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was.",
  "2 Corinthians 5:10": "For we must all appear before the judgment seat of Christ; that every one may receive the things done in his body, according to that he hath done, whether it be good or bad.",
  // --- end appended set ---
  "1 Corinthians 13:4-7": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things.",
  "1 Corinthians 2:16": "For who hath known the mind of the Lord, that he may instruct him? But we have the mind of Christ.",
  "1 Corinthians 4:2": "Moreover it is required in stewards, that a man be found faithful.",
  "1 Corinthians 6:12": "All things are lawful unto me, but all things are not expedient: all things are lawful for me, but I will not be brought under the power of any.",
  "1 Corinthians 9:19-22": "For though I be free from all men, yet have I made myself servant unto all, that I might gain the more. And unto the Jews I became as a Jew, that I might gain the Jews; to them that are under the law, as under the law, that I might gain them that are under the law; To them that are without law, as without law, (being not without law to God, but under the law to Christ,) that I might gain them that are without law. To the weak became I as weak, that I might gain the weak: I am made all things to all men, that I might by all means save some.",
  "1 John 3:20": "For if our heart condemn us, God is greater than our heart, and knoweth all things.",
  "1 John 4:1": "Beloved, believe not every spirit, but try the spirits whether they are of God: because many false prophets are gone out into the world.",
  "1 John 4:16": "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.",
  "1 John 4:17-18": "Herein is our love made perfect, that we may have boldness in the day of judgment: because as he is, so are we in this world. There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.",
  "1 John 4:19": "We love him, because he first loved us.",
  "1 John 4:4": "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world.",
  "1 John 4:7-8": "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God. He that loveth not knoweth not God; for God is love.",
  "1 John 5:14": "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us:",
  "1 John 5:7": "For there are three that bear record in heaven, the Father, the Word, and the Holy Ghost: and these three are one.",
  "1 Peter 1:8": "Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory:",
  "1 Peter 2:21": "For even hereunto were ye called: because Christ also suffered for us, leaving us an example, that ye should follow his steps:",
  "1 Peter 2:24": "Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed.",
  "1 Peter 3:14": "But and if ye suffer for righteousness’ sake, happy are ye: and be not afraid of their terror, neither be troubled;",
  "1 Peter 4:10": "As every man hath received the gift, even so minister the same one to another, as good stewards of the manifold grace of God.",
  "1 Peter 4:12-13": "Beloved, think it not strange concerning the fiery trial which is to try you, as though some strange thing happened unto you: But rejoice, inasmuch as ye are partakers of Christ’s sufferings; that, when his glory shall be revealed, ye may be glad also with exceeding joy.",
  "1 Peter 4:19": "Wherefore let them that suffer according to the will of God commit the keeping of their souls to him in well doing, as unto a faithful Creator.",
  "1 Peter 4:8": "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.",
  "1 Peter 5:8": "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour:",
  "1 Thessalonians 5:17": "Pray without ceasing.",
  "1 Thessalonians 5:21": "Prove all things; hold fast that which is good.",
  "2 Corinthians 10:4-5": "(For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds;) Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ;",
  "2 Corinthians 13:14": "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen.",
  "2 Corinthians 5:17": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
  "2 Corinthians 5:21": "For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.",
  "2 Corinthians 9:7": "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.",
  "2 Peter 1:5-7": "And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge; And to knowledge temperance; and to temperance patience; and to patience godliness; And to godliness brotherly kindness; and to brotherly kindness charity.",
  "2 Peter 3:18": "But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and for ever. Amen.",
  "2 Peter 3:9": "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.",
  "2 Timothy 2:2": "And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also.",
  "2 Timothy 3:12": "Yea, and all that will live godly in Christ Jesus shall suffer persecution.",
  "2 Timothy 3:16-17": "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works.",
  "Acts 17:11": "These were more noble than those in Thessalonica, in that they received the word with all readiness of mind, and searched the scriptures daily, whether those things were so.",
  "Acts 17:27-28": "That they should seek the Lord, if haply they might feel after him, and find him, though he be not far from every one of us: For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring.",
  "Acts 17:29": "Forasmuch then as we are the offspring of God, we ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man’s device.",
  "Acts 4:12": "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.",
  "Acts 5:41": "And they departed from the presence of the council, rejoicing that they were counted worthy to suffer shame for his name.",
  "Colossians 1:17": "And he is before all things, and by him all things consist.",
  "Colossians 2:9": "For in him dwelleth all the fulness of the Godhead bodily.",
  "Colossians 3:14": "And above all these things put on charity, which is the bond of perfectness.",
  "Colossians 3:2": "Set your affection on things above, not on things on the earth.",
  "Colossians 3:23": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;",
  "Colossians 3:9-10": "Lie not one to another, seeing that ye have put off the old man with his deeds; And have put on the new man, which is renewed in knowledge after the image of him that created him:",
  "Daniel 1:17": "As for these four children, God gave them knowledge and skill in all learning and wisdom: and Daniel had understanding in all visions and dreams.",
  "Deuteronomy 6:4": "Hear, O Israel: The LORD our God is one LORD:",
  "Ephesians 1:9-11": "Having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself: That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; even in him: In whom also we have obtained an inheritance, being predestinated according to the purpose of him who worketh all things after the counsel of his own will:",
  "Ephesians 4:13": "Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:",
  "Ephesians 4:22-24": "That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts; And be renewed in the spirit of your mind; And that ye put on the new man, which after God is created in righteousness and true holiness.",
  "Ephesians 4:23": "And be renewed in the spirit of your mind;",
  "Ephesians 4:4-6": "There is one body, and one Spirit, even as ye are called in one hope of your calling; One Lord, one faith, one baptism, One God and Father of all, who is above all, and through all, and in you all.",
  "Ephesians 6:11": "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
  "Ephesians 6:12": "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.",
  "Exodus 3:14": "And God said unto Moses, I AM THAT I AM: and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you.",
  "Ezekiel 18:23": "Have I any pleasure at all that the wicked should die? saith the Lord GOD: and not that he should return from his ways, and live?",
  "Ezekiel 33:11": "Say unto them, As I live, saith the Lord GOD, I have no pleasure in the death of the wicked; but that the wicked turn from his way and live: turn ye, turn ye from your evil ways; for why will ye die, O house of Israel?",
  "Ezekiel 36:26": "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh.",
  "Galatians 5:13": "For, brethren, ye have been called unto liberty; only use not liberty for an occasion to the flesh, but by love serve one another.",
  "Galatians 5:22-23": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.",
  "Genesis 1:26": "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.",
  "Genesis 14:20": "And blessed be the most high God, which hath delivered thine enemies into thy hand. And he gave him tithes of all.",
  "Genesis 17:1": "And when Abram was ninety years old and nine, the LORD appeared to Abram, and said unto him, I am the Almighty God; walk before me, and be thou perfect.",
  "Genesis 28:22": "And this stone, which I have set for a pillar, shall be God’s house: and of all that thou shalt give me I will surely give the tenth unto thee.",
  "Hebrews 13:8": "Jesus Christ the same yesterday, and to day, and for ever.",
  "Hebrews 4:12": "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.",
  "Hebrews 4:13": "Neither is there any creature that is not manifest in his sight: but all things are naked and opened unto the eyes of him with whom we have to do.",
  "Hebrews 4:9-11": "There remaineth therefore a rest to the people of God. For he that is entered into his rest, he also hath ceased from his own works, as God did from his. Let us labour therefore to enter into that rest, lest any man fall after the same example of unbelief.",
  "Hebrews 5:14": "But strong meat belongeth to them that are of full age, even those who by reason of use have their senses exercised to discern both good and evil.",
  "Hebrews 6:1": "Therefore leaving the principles of the doctrine of Christ, let us go on unto perfection; not laying again the foundation of repentance from dead works, and of faith toward God,",
  "Isaiah 26:3": "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
  "Isaiah 44:6": "Thus saith the LORD the King of Israel, and his redeemer the LORD of hosts; I am the first, and I am the last; and beside me there is no God.",
  "Isaiah 46:9-10": "Remember the former things of old: for I am God, and there is none else; I am God, and there is none like me, Declaring the end from the beginning, and from ancient times the things that are not yet done, saying, My counsel shall stand, and I will do all my pleasure:",
  "Isaiah 53:5": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
  "Isaiah 55:11": "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
  "Isaiah 55:8-9": "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
  "Isaiah 9:6": "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.",
  "James 1:2-3": "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.",
  "James 1:4": "But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.",
  "James 4:7": "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
  "James 5:16": "Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.",
  "James 5:19-20": "Brethren, if any of you do err from the truth, and one convert him; Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins.",
  "Jeremiah 23:23-24": "Am I a God at hand, saith the LORD, and not a God afar off? Can any hide himself in secret places that I shall not see him? saith the LORD. Do not I fill heaven and earth? saith the LORD.",
  "Jeremiah 29:11": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
  "Jeremiah 32:17": "Ah Lord GOD! behold, thou hast made the heaven and the earth by thy great power and stretched out arm, and there is nothing too hard for thee:",
  "Jeremiah 32:27": "Behold, I am the LORD, the God of all flesh: is there any thing too hard for me?",
  "John 1:1": "In the beginning was the Word, and the Word was with God, and the Word was God.",
  "John 1:14": "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.",
  "John 10:30": "I and my Father are one.",
  "John 13:34-35": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another.",
  "John 14:27": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
  "John 14:6": "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
  "John 14:9-11": "Jesus saith unto him, Have I been so long time with you, and yet hast thou not known me, Philip? he that hath seen me hath seen the Father; and how sayest thou then, Shew us the Father? Believest thou not that I am in the Father, and the Father in me? the words that I speak unto you I speak not of myself: but the Father that dwelleth in me, he doeth the works. Believe me that I am in the Father, and the Father in me: or else believe me for the very works’ sake.",
  "John 15:11": "These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.",
  "John 15:13": "Greater love hath no man than this, that a man lay down his life for his friends.",
  "John 15:5": "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.",
  "John 16:33": "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
  "John 17:20-21": "Neither pray I for these alone, but for them also which shall believe on me through their word; That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me.",
  "John 3:16": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
  "John 3:17": "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
  "John 3:18": "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
  "John 3:3": "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
  "John 3:36": "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him.",
  "John 4:24": "God is a Spirit: and they that worship him must worship him in spirit and in truth.",
  "John 8:10-11": "When Jesus had lifted up himself, and saw none but the woman, he said unto her, Woman, where are those thine accusers? hath no man condemned thee? She said, No man, Lord. And Jesus said unto her, Neither do I condemn thee: go, and sin no more.",
  "John 8:58": "Jesus said unto them, Verily, verily, I say unto you, Before Abraham was, I am.",
  "Leviticus 27:30": "And all the tithe of the land, whether of the seed of the land, or of the fruit of the tree, is the LORD’S: it is holy unto the LORD.",
  "Luke 13:3": "I tell you, Nay: but, except ye repent, ye shall all likewise perish.",
  "Luke 16:10": "He that is faithful in that which is least is faithful also in much: and he that is unjust in the least is unjust also in much.",
  "Luke 16:19-31": "There was a certain rich man, which was clothed in purple and fine linen, and fared sumptuously every day: And there was a certain beggar named Lazarus, which was laid at his gate, full of sores, And desiring to be fed with the crumbs which fell from the rich man’s table: moreover the dogs came and licked his sores. And it came to pass, that the beggar died, and was carried by the angels into Abraham’s bosom: the rich man also died, and was buried; And in hell he lift up his eyes, being in torments, and seeth Abraham afar off, and Lazarus in his bosom. And he cried and said, Father Abraham, have mercy on me, and send Lazarus, that he may dip the tip of his finger in water, and cool my tongue; for I am tormented in this flame. But Abraham said, Son, remember that thou in thy lifetime receivedst thy good things, and likewise Lazarus evil things: but now he is comforted, and thou art tormented. And beside all this, between us and you there is a great gulf fixed: so that they which would pass from hence to you cannot; neither can they pass to us, that would come from thence. Then he said, I pray thee therefore, father, that thou wouldest send him to my father’s house: For I have five brethren; that he may testify unto them, lest they also come into this place of torment. Abraham saith unto him, They have Moses and the prophets; let them hear them. And he said, Nay, father Abraham: but if one went unto them from the dead, they will repent. And he said unto him, If they hear not Moses and the prophets, neither will they be persuaded, though one rose from the dead.",
  "Luke 19:10": "For the Son of man is come to seek and to save that which was lost.",
  "Luke 2:49": "And he said unto them, How is it that ye sought me? wist ye not that I must be about my Father’s business?",
  "Luke 22:42": "Saying, Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done.",
  "Malachi 3:6": "For I am the LORD, I change not; therefore ye sons of Jacob are not consumed.",
  "Malachi 3:8-10": "Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings. Ye are cursed with a curse: for ye have robbed me, even this whole nation. Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.",
  "Mark 10:43-45": "But so shall it not be among you: but whosoever will be great among you, shall be your minister: And whosoever of you will be the chiefest, shall be servant of all. For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.",
  "Mark 9:43-48": "And if thy hand offend thee, cut it off: it is better for thee to enter into life maimed, than having two hands to go into hell, into the fire that never shall be quenched: Where their worm dieth not, and the fire is not quenched. And if thy foot offend thee, cut it off: it is better for thee to enter halt into life, than having two feet to be cast into hell, into the fire that never shall be quenched: Where their worm dieth not, and the fire is not quenched. And if thine eye offend thee, pluck it out: it is better for thee to enter into the kingdom of God with one eye, than having two eyes to be cast into hell fire: Where their worm dieth not, and the fire is not quenched.",
  "Matthew 10:28": "And fear not them which kill the body, but are not able to kill the soul: but rather fear him which is able to destroy both soul and body in hell.",
  "Matthew 19:26": "But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible.",
  "Matthew 25:41-46": "Then shall he say also unto them on the left hand, Depart from me, ye cursed, into everlasting fire, prepared for the devil and his angels: For I was an hungred, and ye gave me no meat: I was thirsty, and ye gave me no drink: I was a stranger, and ye took me not in: naked, and ye clothed me not: sick, and in prison, and ye visited me not. Then shall they also answer him, saying, Lord, when saw we thee an hungred, or athirst, or a stranger, or naked, or sick, or in prison, and did not minister unto thee? Then shall he answer them, saying, Verily I say unto you, Inasmuch as ye did it not to one of the least of these, ye did it not to me. And these shall go away into everlasting punishment: but the righteous into life eternal.",
  "Matthew 28:19-20": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen.",
  "Matthew 4:4": "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.",
  "Matthew 5:10-12": "Blessed are they which are persecuted for righteousness sake: for theirs is the kingdom of heaven. Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake. Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you.",
  "Matthew 5:48": "Be ye therefore perfect, even as your Father which is in heaven is perfect.",
  "Matthew 6:33": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
  "Matthew 7:13-14": "Enter ye in at the strait gate: for wide is the gate, and broad is the way, that leadeth to destruction, and many there be which go in thereat: Because strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it.",
  "Matthew 7:21": "Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven; but he that doeth the will of my Father which is in heaven.",
  "Matthew 7:7": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:",
  "Nehemiah 8:10": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.",
  "Philippians 1:29": "For unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake;",
  "Philippians 1:6": "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:",
  "Philippians 2:3-4": "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves. Look not every man on his own things, but every man also on the things of others.",
  "Philippians 3:10": "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death;",
  "Philippians 3:12": "Not as though I had already attained, either were already perfect: but I follow after, if that I may apprehend that for which also I am apprehended of Christ Jesus.",
  "Philippians 3:13-14": "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus.",
  "Philippians 4:4": "Rejoice in the Lord alway: and again I say, Rejoice.",
  "Philippians 4:6-7": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
  "Philippians 4:8": "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.",
  "Proverbs 11:30": "The fruit of the righteous is a tree of life; and he that winneth souls is wise.",
  "Proverbs 14:15": "The simple believeth every word: but the prudent man looketh well to his going.",
  "Proverbs 16:3": "Commit thy works unto the LORD, and thy thoughts shall be established.",
  "Proverbs 16:9": "A man’s heart deviseth his way: but the LORD directeth his steps.",
  "Proverbs 18:13": "He that answereth a matter before he heareth it, it is folly and shame unto him.",
  "Proverbs 19:21": "There are many devices in a man’s heart; nevertheless the counsel of the LORD, that shall stand.",
  "Proverbs 22:29": "Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men.",
  "Proverbs 3:5-6": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
  "Proverbs 3:9-10": "Honour the LORD with thy substance, and with the firstfruits of all thine increase: So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.",
  "Proverbs 4:23": "Keep thy heart with all diligence; for out of it are the issues of life.",
  "Proverbs 4:7": "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.",
  "Psalm 100:1-2": "Make a joyful noise unto the LORD, all ye lands. Serve the LORD with gladness: come before his presence with singing.",
  "Psalm 119:105": "Thy word is a lamp unto my feet, and a light unto my path.",
  "Psalm 139:1-4": "O LORD, thou hast searched me, and known me. Thou knowest my downsitting and mine uprising, thou understandest my thought afar off. Thou compassest my path and my lying down, and art acquainted with all my ways. For there is not a word in my tongue, but, lo, O LORD, thou knowest it altogether.",
  "Psalm 139:7-10": "Whither shall I go from thy spirit? or whither shall I flee from thy presence? If I ascend up into heaven, thou art there: if I make my bed in hell, behold, thou art there. If I take the wings of the morning, and dwell in the uttermost parts of the sea; Even there shall thy hand lead me, and thy right hand shall hold me.",
  "Psalm 16:11": "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
  "Psalm 34:3": "O magnify the LORD with me, and let us exalt his name together.",
  "Psalm 37:5": "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.",
  "Psalm 90:2": "Before the mountains were brought forth, or ever thou hadst formed the earth and the world, even from everlasting to everlasting, thou art God.",
  "Psalm 95:6": "O come, let us worship and bow down: let us kneel before the LORD our maker.",
  "Revelation 1:4": "John to the seven churches which are in Asia: Grace be unto you, and peace, from him which is, and which was, and which is to come; and from the seven Spirits which are before his throne;",
  "Revelation 1:8": "I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.",
  "Revelation 19:6": "And I heard as it were the voice of a great multitude, and as the voice of many waters, and as the voice of mighty thunderings, saying, Alleluia: for the Lord God omnipotent reigneth.",
  "Revelation 20:15": "And whosoever was not found written in the book of life was cast into the lake of fire.",
  "Revelation 21:4": "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.",
  "Revelation 21:8": "But the fearful, and unbelieving, and the abominable, and murderers, and whoremongers, and sorcerers, and idolaters, and all liars, shall have their part in the lake which burneth with fire and brimstone: which is the second death.",
  "Revelation 22:13": "I am Alpha and Omega, the beginning and the end, the first and the last.",
  "Revelation 4:8": "And the four beasts had each of them six wings about him; and they were full of eyes within: and they rest not day and night, saying, Holy, holy, holy, Lord God Almighty, which was, and is, and is to come.",
  "Romans 1:20": "For the invisible things of him from the creation of the world are clearly seen, being understood by the things that are made, even his eternal power and Godhead; so that they are without excuse:",
  "Romans 10:13": "For whosoever shall call upon the name of the Lord shall be saved.",
  "Romans 10:9": "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
  "Romans 12:1": "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service.",
  "Romans 12:2": "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
  "Romans 5:1": "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:",
  "Romans 5:8": "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
  "Romans 6:23": "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.",
  "Romans 8:1": "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
  "Romans 8:17": "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.",
  "Romans 8:18": "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
  "Romans 8:28": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",

  // --- Appended 2026-07-06 for "The Way Up" game (wilderness -> the table) ---
  // Sourced VERBATIM from the in-repo public-domain KJV (app/public/bible/kjv/*.json,
  // materialized by scripts/fetch-full-kjv.mjs), never typed from memory (DR-0076).
  "Deuteronomy 8:2": "And thou shalt remember all the way which the LORD thy God led thee these forty years in the wilderness, to humble thee, and to prove thee, to know what was in thine heart, whether thou wouldest keep his commandments, or no.",
  "Deuteronomy 8:3": "And he humbled thee, and suffered thee to hunger, and fed thee with manna, which thou knewest not, neither did thy fathers know; that he might make thee know that man doth not live by bread only, but by every word that proceedeth out of the mouth of the LORD doth man live.",
  "Deuteronomy 8:18": "But thou shalt remember the LORD thy God: for it is he that giveth thee power to get wealth, that he may establish his covenant which he sware unto thy fathers, as it is this day.",
  "Genesis 39:2": "And the LORD was with Joseph, and he was a prosperous man; and he was in the house of his master the Egyptian.",
  "Genesis 39:9": "There is none greater in this house than I; neither hath he kept back any thing from me but thee, because thou art his wife: how then can I do this great wickedness, and sin against God?",
  "James 4:10": "Humble yourselves in the sight of the Lord, and he shall lift you up.",
  "1 Peter 5:6": "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:",
  "Matthew 23:12": "And whosoever shall exalt himself shall be abased; and he that shall humble himself shall be exalted.",
  "Proverbs 22:7": "The rich ruleth over the poor, and the borrower is servant to the lender.",
  "Proverbs 21:20": "There is treasure to be desired and oil in the dwelling of the wise; but a foolish man spendeth it up.",
  "3 John 1:2": "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.",
  "Joshua 1:8": "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.",
  "Psalm 1:3": "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.",
  "Deuteronomy 28:1": "And it shall come to pass, if thou shalt hearken diligently unto the voice of the LORD thy God, to observe and to do all his commandments which I command thee this day, that the LORD thy God will set thee on high above all nations of the earth:",
  "Deuteronomy 28:10": "And all people of the earth shall see that thou art called by the name of the LORD; and they shall be afraid of thee.",
  "Deuteronomy 28:13": "And the LORD shall make thee the head, and not the tail; and thou shalt be above only, and thou shalt not be beneath; if that thou hearken unto the commandments of the LORD thy God, which I command thee this day, to observe and to do them:",
  "Psalm 23:5": "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
  "Psalm 110:1": "The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.",
  "Matthew 5:5": "Blessed are the meek: for they shall inherit the earth.",
  "Genesis 50:20": "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive.",
  "Job 42:10": "And the LORD turned the captivity of Job, when he prayed for his friends: also the LORD gave Job twice as much as he had before.",
  "Job 42:12": "So the LORD blessed the latter end of Job more than his beginning: for he had fourteen thousand sheep, and six thousand camels, and a thousand yoke of oxen, and a thousand she asses.",
  "2 Timothy 1:7": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
  "Romans 8:37": "Nay, in all these things we are more than conquerors through him that loved us.",
  "Revelation 3:21": "To him that overcometh will I grant to sit with me in my throne, even as I also overcame, and am set down with my Father in his throne.",
  "Luke 6:38": "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again.",

  // --- Appended 2026-07-06 for "The Way Up" game (wilderness -> the table) ---
  // Sourced VERBATIM from the in-repo public-domain KJV (app/public/bible/kjv/*.json,
  // materialized by scripts/fetch-full-kjv.mjs), never typed from memory (DR-0076).
  "Romans 8:15": "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father.",

  // --- Appended 2026-07-06 for the Generations "Stewardship & Legacy" deck ---
  // Sourced VERBATIM from the in-repo public-domain KJV (app/public/bible/kjv/*.json),
  // never typed from memory (DR-0076).
  "Genesis 1:11": "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.",
  "Proverbs 27:18": "Whoso keepeth the fig tree shall eat the fruit thereof: so he that waiteth on his master shall be honoured.",
  "Proverbs 24:27": "Prepare thy work without, and make it fit for thyself in the field; and afterwards build thine house.",
  "Luke 14:28": "For which of you, intending to build a tower, sitteth not down first, and counteth the cost, whether he have sufficient to finish it?",
  "2 Kings 4:7": "Then she came and told the man of God. And he said, Go, sell the oil, and pay thy debt, and live thou and thy children of the rest.",
  "Romans 13:8": "Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law.",
  "Proverbs 13:22": "A good man leaveth an inheritance to his children’s children: and the wealth of the sinner is laid up for the just.",
  "Deuteronomy 8:17": "And thou say in thine heart, My power and the might of mine hand hath gotten me this wealth.",
  "Isaiah 42:8": "I am the LORD: that is my name: and my glory will I not give to another, neither my praise to graven images.",
  "Psalm 115:1": "Not unto us, O LORD, not unto us, but unto thy name give glory, for thy mercy, and for thy truth’s sake.",
  "1 Corinthians 4:7": "For who maketh thee to differ from another? and what hast thou that thou didst not receive? now if thou didst receive it, why dost thou glory, as if thou hadst not received it?",

  // --- Appended 2026-07-06 for the Generations "Pride & the Increase" deck ---
  // Sourced VERBATIM from the in-repo public-domain KJV (app/public/bible/kjv/*.json),
  // never typed from memory (DR-0076).
  "Proverbs 16:18": "Pride goeth before destruction, and an haughty spirit before a fall.",
  "Daniel 4:37": "Now I Nebuchadnezzar praise and extol and honour the King of heaven, all whose works are truth, and his ways judgment: and those that walk in pride he is able to abase.",
  "1 Corinthians 3:7": "So then neither is he that planteth any thing, neither he that watereth; but God that giveth the increase.",
  "Psalm 127:1": "Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain.",
};
