// =============================================================================
// showcase — the gallery lane (0092): her work, front-screen, factory-reusable
// =============================================================================
// Thin client over the 0092 RPCs + the public bucket. Reads are anon-safe;
// writes are steward-gated server-side. sortPieces is pure (pinned favorites
// first, then newest — "sorted by whatever makes sense").
// =============================================================================
import supabase from './supabase.js';
import { publicRpc } from './public-rpc.js';

const BUCKET = 'moore-showcase';

// Public read rides publicRpc (anon + hard deadline), NEVER the shared client:
// the shared client's getSession() waits on a cross-tab auth lock, and a wedged
// PoeTech window on the same device hangs it forever (the 2026-07-07 "gallery
// never loads" hang). Steward WRITES below keep the real client — they need
// the session.
export async function fetchShowcase(instanceSlug) {
  const { data, error } = await publicRpc('moore_showcase', { p_instance_slug: instanceSlug });
  if (error) return { ok: false, pieces: [] };
  return { ok: true, pieces: data || [] };
}

// SERVE THE PICTURES FROM CLOUDFLARE, NOT FROM METERED STORAGE.
//
// Darrell 2026-08-14, after the egress lockout: "resize the moore-showcase
// images and move them to cloudflare". This bucket held camera originals —
// 12 objects, 29.7 MB, with the top three alone at 24.4 MB — served at full
// size to phones that display them a few hundred pixels wide, billing Supabase
// egress against a 5 GB monthly quota every time the gallery loaded. Image
// transformations are not available on the free plan, so there was no setting
// to fix; the picture itself had to move.
//
// `showcase-localized.json` maps a bucket path to a right-sized copy committed
// under app/public/showcase/, which Cloudflare Pages serves same-origin and
// which costs Supabase nothing. It is generated by scripts/showcase-localize.mjs
// and is `{}` until that has run — an empty map simply means every image falls
// through to the original, which is the correct behaviour, not a broken state.
//
// THE ORIGINALS ARE NEVER DELETED. They remain in the bucket as the fallback
// below and as the source for any future re-encode. A localized copy that turns
// out wrong is always recoverable, and nothing in this change destroys Shay's
// photographs.
import LOCALIZED from './showcase-localized.json';

/** Same-origin path for a localized image, or null when there is not one. */
export function localizedShowcasePath(imagePath) {
  const rel = imagePath && LOCALIZED[imagePath];
  return rel ? `/showcase/${rel}` : null;
}

export function showcaseImageUrl(imagePath) {
  if (!imagePath) return null;
  if (/^https?:\/\//.test(imagePath)) return imagePath;
  // Cloudflare first — same-origin, unmetered, already right-sized.
  const local = localizedShowcasePath(imagePath);
  if (local) return local;
  try {
    const { data } = supabase.storage.from(BUCKET).getPublicUrl(imagePath);
    return data?.publicUrl || null;
  } catch { return null; }
}

// Steward: upload the image file, then register the piece (instance pinned
// server-side by the RPC). Returns { ok } or a structured error.
export async function addPiece({ instanceSlug, title, description = '', productType = 'other', file, priceCents = null }) {
  if (!file || !title?.trim()) return { ok: false, error: 'title-and-image-required' };
  const slug = `sp-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
  const ext = (file.name || 'jpg').split('.').pop().toLowerCase().replace(/[^a-z0-9]/g, '') || 'jpg';
  const path = `${instanceSlug}/${slug}.${ext}`;
  const up = await supabase.storage.from(BUCKET).upload(path, file, { upsert: false });
  if (up.error) return { ok: false, error: up.error.message || 'upload-failed' };
  const { error } = await supabase.rpc('add_showcase_piece', {
    p_instance_slug: instanceSlug, p_slug: slug, p_title: title,
    p_description: description, p_product_type: productType, p_image_path: path,
    p_price_cents: priceCents,
  });
  if (error) return { ok: false, error: error.message || 'register-failed' };
  return { ok: true, slug };
}

// Edit an EXISTING piece in place — title/description/price, no re-upload
// (Shay 2026-07-08: old pieces needed delete-and-re-add just to get a price).
// A null priceCents honestly clears the price.
export async function updatePiece({ instanceSlug, slug, title, description = '', priceCents = null }) {
  if (!slug || !title?.trim()) return { ok: false, error: 'title-required' };
  const { data, error } = await supabase.rpc('update_showcase_piece', {
    p_instance_slug: instanceSlug, p_slug: slug, p_title: title,
    p_description: description, p_price_cents: priceCents,
  });
  if (error) return { ok: false, error: error.message || 'update-failed' };
  return { ok: data === true };
}

// Dollars-string → cents, honestly: '' / garbage → null (no price), never 0.
export function priceInputToCents(raw) {
  const t = String(raw ?? '').replace(/[$,\s]/g, '');
  if (!t) return null;
  const n = Number(t);
  if (!Number.isFinite(n) || n <= 0) return null;
  return Math.round(n * 100);
}

export async function setPin(instanceSlug, slug, pinned) {
  const { error } = await supabase.rpc('set_showcase_pin', { p_instance_slug: instanceSlug, p_slug: slug, p_pinned: pinned });
  return { ok: !error };
}
export async function removePiece(instanceSlug, slug) {
  const { error } = await supabase.rpc('delete_showcase_piece', { p_instance_slug: instanceSlug, p_slug: slug });
  return { ok: !error };
}

// Pure: pinned favorites first, then newest. The RPC already orders this way;
// re-sorting client-side keeps the rule true after local pin toggles too.
export function sortPieces(pieces = []) {
  return [...(pieces || [])].sort((a, b) => {
    if (!!b.pinned !== !!a.pinned) return b.pinned ? 1 : -1;
    return String(b.created_at || '').localeCompare(String(a.created_at || ''));
  });
}
