// =============================================================================
// Course bodies · Assessment & diagnosis (DR-0345 build-out, 2026-09-10)
// =============================================================================
// Darrell: "what happened to the whole courses build out?" The starters were
// one paragraph each. These are the full lessons: the concept, how it runs in
// session, a worked example, the pitfalls, what the standard bodies and
// Illinois require, and a self-check. Plain rendering (no Scripture; the
// Word rendering is the course's own strand, on click). Clinical content is
// grounded in the named standards and is Christina's (LCSW) to ratify.
export default {
  'tl-assess-bps-m1': `What it is. A biopsychosocial assessment reads the person as one interacting system rather than a list of complaints. The biological stream holds sleep, appetite, pain, chronic illness, medication and its side effects, substance use, family medical history, and the body's stress signals. The psychological stream holds mood, anxiety, thought patterns, trauma history, coping style, prior treatment and what helped, and how the person makes sense of their own story. The social stream holds relationships, work or school, housing, money, transportation, culture, faith community, legal matters, and the supports or stressors that surround them. None of the three explains the presenting concern alone; the assessment's work is to see how they push on one another.

How it runs in session. Open with the person's own words for why they came, then move through the three streams in a conversational order rather than a checklist, returning to anything that lit up. Ask about the body plainly ("How are you sleeping? What does a bad night do to the next day?"). Ask about the mind with curiosity rather than diagnosis ("When the worry starts, what does it say?"). Ask about the world around them ("Who knows you are here? Who would you call at 2 a.m.?"). Close by reflecting back the connections you heard, and ask whether you have it right; the client is the expert on their life and will correct the map.

A worked example. A woman in her thirties comes in for "stress." Biological: she sleeps five hours, drinks coffee through the afternoon, and has had headaches for months. Psychological: she describes racing thoughts at night and a belief that resting is lazy. Social: she is the only earner since her husband's layoff, and she stopped attending her women's group because there was no time. Read together, the picture is a loop: short sleep feeds irritability and the headaches, the belief about laziness keeps her from resting, the lost group removed the one place she was heard, and the money pressure keeps the whole loop turning. The concern is not "stress"; it is a loop you can now name with her.

Pitfalls. Collecting facts without connecting them; letting one stream dominate (a purely psychological read of a sleep problem, or a purely medical read of a grief); skipping the social stream because it feels like "not therapy"; and writing the assessment as a verdict rather than as the client's story in your structure. Watch for your own assumptions about poverty, faith, or family shape entering the social read.

What is required. The NASW Code of Ethics asks that assessment respect self-determination and cultural context, and that services stay within competence; a thorough intake is also where informed consent for the work is grounded. In Illinois the intake is where the confidentiality limits and, for a minor, the consent rules are explained and recorded; the Illinois lesson at the end of this course carries the rules.

Self-check. Can you name one factor in each stream for your last intake, and one way two of them interact? If not, the assessment described the person; it did not yet understand them.`,

  'tl-assess-bps-m2': `What it is. A clinical formulation is the bridge between what you learned and what you will do. It answers, in a few honest sentences, why this person is struggling in this way at this time, and what is likely to help. The "4 Ps" frame keeps it disciplined: predisposing factors (what made the person vulnerable long before now, such as early loss, a family history of depression, or a temperament that runs anxious), precipitating factors (what set it off now, such as a job loss, a diagnosis, a move, a betrayal), perpetuating factors (what keeps it going, such as avoidance, an isolating schedule, a conflict that repeats, or a belief that asking for help is failure), and protective factors (the strengths and supports to build on, such as faith, a steady friend, humor, a history of getting through hard things, a job that still holds).

How it runs in session. Write the formulation after the assessment, not during it, and then bring it back to the client in plain words: "Here is what I think is going on; tell me where I am wrong." A formulation the client recognises becomes the treatment plan's map; one they reject is data about what you missed. Revisit it every few sessions. A formulation is a working hypothesis, not a verdict; when a new fact arrives that does not fit, the formulation changes, not the fact.

A worked example. The woman from the previous lesson: predisposing, a mother who modelled rest as weakness and a lifelong tendency to over-function; precipitating, her husband's layoff four months ago; perpetuating, five-hour nights, afternoon caffeine, the dropped women's group, and the belief that resting is laziness; protective, a marriage that is still warm, a faith she names as her anchor, and a supervisor who would grant flexibility if asked. The targets write themselves: sleep and caffeine (biological), the laziness belief (psychological), the group and the supervisor conversation (social). The protective factors are where the plan leans.

Pitfalls. Confusing a diagnosis with a formulation (a code names a pattern; a formulation explains this person); loading the predisposing column with history and leaving the perpetuating column empty (the perpetuating factors are what treatment can change this month); writing protective factors as an afterthought; and never sharing the formulation with the client, which turns a collaboration into an assessment done to them.

What is required. Evidence-based practice as the APA defines it integrates the best research with clinical expertise and the client's characteristics, culture and preferences; the formulation is where those three meet. Illinois documentation standards expect the record to show a reasoned basis for the plan; a formulation is that basis in writing.

Self-check. Read your last formulation aloud to yourself as if to the client. Does it explain why now, name what keeps the problem alive, and say what you will lean on? If any of the three is missing, the plan that follows is guessing.`,

  'tl-assess-dsm-m1': `What it is. The DSM-5-TR is a shared language: a set of agreed descriptions that let clinicians, physicians, insurers and researchers mean the same thing when they say "major depressive disorder" or "generalized anxiety disorder." It is a tool for communication and for matching a person to treatments that were studied on people with similar patterns. It is not a verdict on who the person is, and it is not a cause. Every diagnosis in it describes a pattern of experience and behaviour over time; it does not say why the pattern exists or what it means to the person living it.

How it runs in session. You gather the picture first (the biopsychosocial assessment), and only then ask whether the picture meets criteria, checking duration, number of symptoms, functional impairment, and the exclusions (a medical cause, a substance, a bereavement that is running its natural course). You say the diagnosis to the client in plain words, with what it is for: "This pattern has a name, and the name is useful because it tells us which treatments have the best evidence. It is a description of what you have been living with, not a label on you." You record the reasoning, not only the code.

A worked example. A man reports two months of low mood, early waking, loss of interest, guilt, and trouble concentrating, with no manic history, no substance change, and a clean medical work-up. That meets criteria for a major depressive episode, and naming it opens the door to treatments with strong evidence. His sister, describing similar sadness three weeks after their father's death, with waves that come and go and moments of real warmth remembering him, does not; grief has its own course, and a diagnosis would misname it.

Pitfalls. Diagnosing from a checklist without the duration and impairment questions; letting an insurer's need for a code drive the clinical judgment; reifying the label so that "she is borderline" replaces "she shows this pattern under these conditions"; forgetting that many diagnoses share symptoms and that the first fit is not always the best fit; and giving a diagnosis without explaining what it is for.

What is required. Practice within competence: a social worker diagnoses within the scope the Illinois Clinical Social Work and Social Work Practice Act grants a licensed clinical social worker, and refers for medical or psychiatric evaluation when the picture calls for it. The record must show the basis for any diagnosis given. TLC's house position on diagnosis in faith-integrated, culturally humble practice is Christina's to state; this lesson carries the general standard.

Self-check. For the last diagnosis you recorded, can you name the duration you confirmed, the impairment you observed, and the exclusion you ruled out? If not, you named a pattern you did not yet establish.`,

  'tl-assess-dsm-m2': `What it is. Differential thinking is the discipline of holding more than one explanation open until the evidence settles it. Two people with the same three symptoms may have different conditions; the same condition looks different across cultures, ages, and life circumstances. The DSM-5-TR itself carries a Cultural Formulation Interview because the authors knew that distress is expressed through a person's culture: somatic complaints where feelings are not spoken, spiritual language for what a clinic would call panic, a "normal" level of worry in a community that has real reasons to worry.

How it runs in session. Before settling on a diagnosis, ask what else could produce this picture: a medical condition (thyroid, anaemia, sleep apnoea), a medication or substance, a reaction to a real and recent hardship, a developmental difference, a trauma response, or a culturally patterned way of expressing distress. Ask the client how their own family or community would describe what is happening and what they think is causing it; the answers often reorder your list. When two explanations remain, name the uncertainty in the record and plan the next observation that would separate them.

A worked example. A recent immigrant describes chest tightness, heat in the head, and fear that something is wrong with his heart, worse when he thinks about his family overseas. A quick read says panic disorder. A differential read asks: has a physician examined the heart; is the fear proportionate to a real danger to his family; how does his community name this experience; is this a trauma response to what he left. The answer may still be panic, but now it is a conclusion, not an assumption, and the plan can include the cardiology visit and the community's own frame.

Pitfalls. Anchoring on the first diagnosis that fits; reading a culturally normal response to real hardship as pathology; reading pathology as "just culture" and missing a treatable condition; skipping the medical rule-out because the client "seems anxious"; and treating the DSM's cultural notes as an appendix rather than part of the assessment.

What is required. Cultural competence is a mandated part of Illinois social work continuing education, and the NASW Code names cultural awareness and social diversity as an ethical duty; differential thinking across culture is that duty applied to diagnosis. Referral for medical evaluation when a physical cause is plausible is part of practising within competence.

Self-check. For your last diagnosis, name two alternatives you considered and what ruled each out. If you cannot, the diagnosis was a first impression that was never tested.`,

  'tl-assess-screen-m1': `What it is. A standardized screener is a short, validated questionnaire that measures the severity of a symptom pattern on a known scale. The PHQ-9 measures depressive symptoms over the past two weeks on a 0 to 27 scale, with 10 or more usually read as moderate; the GAD-7 measures anxiety on a 0 to 21 scale with the same rough threshold; the PCL-5 screens for post-traumatic stress; the AUDIT screens alcohol use. A screener does three things: it flags who needs a fuller assessment, it gives a baseline number, and it lets you measure change over time. It does not diagnose. Only a clinical assessment does that.

How it runs in session. Give the screener at intake and then at regular intervals (every session in brief work, every few sessions otherwise). Explain what it is for: "This is a ruler, not a verdict; it lets us both see whether things are moving." Score it in front of the client and discuss the items that stand out, especially any item about self-harm, which is always followed up in conversation the same session. Record the score and date so the trend is visible.

A worked example. A client scores 17 on the PHQ-9 at intake, 14 four weeks later, and 9 at eight weeks. The trend confirms the plan is working and gives the client evidence of their own progress on a day they feel nothing has changed. A different client scores 8 at intake and 15 six weeks later: the number says the plan needs revisiting before the client says it. In both cases the screener started a conversation the clinician might otherwise have missed.

Pitfalls. Treating a score as a diagnosis; treating a cut-off as a wall (a 9 is not "fine" and a 10 is not "sick"); using a screener that was not validated in the client's language or culture and trusting the number anyway; giving a screener and not discussing it; and forgetting the self-harm item.

What is required. Measurement-based care is a recognised evidence-based practice in the APA's sense; screener results belong in the record with their dates. Under Illinois confidentiality law screener results are part of the confidential record and travel only with consent. Any screener response about suicidal thinking triggers the safety assessment this library's crisis course teaches.

Self-check. Name the screener you use most, its scale, and its usual threshold. Then name one population for whom you would question its numbers. If you cannot do the second, you are trusting the ruler more than the person.`,
};
